-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Dec 11, 2023 at 09:42 AM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `simple_blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogs`
--

CREATE TABLE `blogs` (
  `id` int(11) NOT NULL,
  `title` varchar(100) NOT NULL,
  `subtitle` varchar(200) NOT NULL,
  `content` text NOT NULL,
  `date_created` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `blogs`
--

INSERT INTO `blogs` (`id`, `title`, `subtitle`, `content`, `date_created`) VALUES
(7, 'The Art of Gaming', 'Exploring the Thrills, Challenges, and Community of the Gamer Universe', 'In the ever-expanding universe of gaming, a realm of pixels and polygons, there lies an art form that transcends mere entertainment. The controller becomes a paintbrush, and the screen, a canvas for immersive experiences that captivate hearts and minds.\r\n\r\nEmbracing the Game: As we embark on our journey into the vast landscapes of virtual worlds, we encounter not just games but stories waiting to be unfolded. From epic adventures to heart-pounding battles, each game offers a unique narrative, drawing players into a tapestry of emotions and experiences.\r\n\r\nCommunity and Connection: Beyond the pixels, gaming is about the people who share these virtual spaces. Communities form, alliances are forged, and friendships blossom. Whether teaming up for a cooperative mission or competing in the arena, the social fabric of gaming weaves a network that spans the globe.\r\n\r\nChallenges and Triumphs: Just as in any art form, mastering the craft of gaming requires dedication, skill, and a willingness to face challenges head-on. From overcoming intricate puzzles to conquering formidable foes, gamers find joy in the journey, relishing the sweet taste of victory after hard-fought battles.\r\n\r\nTechnology and Innovation: The gaming landscape is ever-evolving, driven by cutting-edge technology and boundless creativity. Virtual reality, augmented reality, and immersive storytelling techniques redefine the boundaries of what is possible, ensuring that the future of gaming holds limitless potential.\r\n\r\nBeyond the Screen: Gaming is not confined to the digital realm; it spills over into our daily lives, influencing culture, music, and even fashion. The gaming community is a vibrant and diverse tapestry, breaking stereotypes and celebrating individuality.', '2023-12-11 08:21:26'),
(8, 'Nakai San Influence', 'Exploring Different brand but same passion for car', 'In the realm of automotive aficionados, the heartbeat of the enthusiast is synchronized with the revving engines, the sleek curves of well-crafted machines, and the intoxicating scent of burning rubber. Join us on a journey through the exhilarating world of cars, where passion meets horsepower.\r\n\r\nThe Pulse of Performance: Every car is a testament to engineering prowess and design ingenuity. From the roar of a muscle car tearing down the open road to the precision of a high-performance supercar navigating a track, the symphony of engines is a language spoken by enthusiasts worldwide.\r\n\r\nTimeless Classics and Modern Marvels: Delve into the archives of automotive history, where classics such as the roaring \'60s muscle cars and elegant vintage models take center stage. Simultaneously, explore the cutting-edge innovations of the present and future, where electric vehicles, hybrids, and autonomous driving redefine the landscape.\r\n\r\nCar Culture and Community: Being a car enthusiast is not just about the machines; it\'s a lifestyle. Car meets, rallies, and shows become canvases where enthusiasts showcase their pride and joy. The camaraderie among gearheads is a bond forged by a shared love for all things automotive.\r\n\r\nBehind the Wheel Adventures: Whether it\'s a scenic drive through winding mountain roads or the adrenaline rush of a track day, the thrill of being behind the wheel is unmatched. Car enthusiasts find joy in the connection between driver and machine, where every turn of the steering wheel is a dance of precision and control.\r\n\r\nRestoration and Customization: Witness the artistry of restoration projects, where classic cars are brought back to life with meticulous attention to detail. Explore the world of customization, where enthusiasts turn their vehicles into unique expressions of personal style and creativity.', '2023-12-11 08:25:47'),
(9, 'Toy Collector Journey', ' Unwrapping the Nostalgia, Craftsmanship, and Joy of Toy Collection', 'Nostalgia Unboxed: As collectors, we embark on a journey to reclaim pieces of our childhood. Vintage action figures, classic board games, and iconic dolls transport us back to a time when imagination knew no bounds. Each toy is a time machine, unlocking memories and evoking the carefree spirit of youth.\r\n\r\nCraftsmanship in Miniature: From intricately designed model trains to meticulously crafted scale replicas, the world of toy collecting is a celebration of craftsmanship in miniature. Explore the artistry and attention to detail that transform ordinary materials into extraordinary creations, capturing the essence of beloved characters and vehicles.\r\n\r\nDiverse Collections, Unique Stories: Toy collectors are a diverse community, each with a unique story to tell through their collections. Whether it\'s amassing a set of rare action figures, curating vintage dolls, or showcasing an array of model cars, the collector\'s journey is a testament to passion, dedication, and a keen eye for the extraordinary.\r\n\r\nConnecting Generations: The magic of toys knows no age limit. As collectors, we bridge generational gaps, sharing the joy of our cherished possessions with younger enthusiasts. A well-preserved toy becomes a time capsule, passing on the tales of bygone eras and sparking the imagination of a new generation.\r\n\r\nHunting for Hidden Gems: The thrill of the hunt is a cornerstone of toy collecting. From antique shops to online auctions, collectors eagerly seek out hidden gems to add to their troves. The joy of discovery and the anticipation of finding that elusive piece make the hunt as rewarding as the collection itself.', '2023-12-11 08:24:15'),
(10, ' A Son\'s Journey', ' Reflections on the Bonds That Shape Us and the Paths We Choose', 'As a son, life unfolds as a poignant tapestry woven with the threads of familial ties, shared memories, and the enduring lessons passed down through generations. Join me on a heartfelt journey, exploring the unique perspective of being a son—navigating the complexities of relationships, discovering one\'s identity, and embracing the profound impact of family.\r\n\r\nRoots of Identity: The journey of a son begins with a deep connection to his roots. Family stories, traditions, and the wisdom of elders shape the foundation of identity. From the cherished tales of ancestors to the lessons whispered by the wind of shared experiences, the son discovers his place within the family narrative.\r\n\r\nBond of Unconditional Love: The bond between a son and his parents is a tapestry of unconditional love. Through the highs and lows, victories and defeats, this bond remains a source of strength, support, and the unwavering belief that, in every step, there is a guiding hand and a cheering heart.\r\n\r\nLegacy and Lessons: As a son, the journey involves not only embracing the legacy inherited but also contributing to the ongoing story. Lessons learned from parents, siblings, and extended family members become the compass guiding decisions, shaping character, and defining the legacy to be passed on to future generations.\r\n\r\nEvolving Relationships: The dynamics between parents and sons evolve over time, transforming from the tender moments of childhood to the nuanced conversations of adulthood. From mentorship to camaraderie, the relationship grows, mirroring the ever-changing landscape of life.\r\n\r\nShared Memories and Milestones: From the first steps to significant milestones, the son and his family weave a tapestry of shared memories. Birthdays, holidays, and everyday moments become threads in the intricate design of a life shared with loved ones.', '2023-12-11 08:26:04'),
(11, 'The Art of Living', ' Balancing Passion, Well-being, and Personal Growth', 'Passions That Ignite the Soul: At the heart of a vibrant lifestyle lies a tapestry of passions. Whether it\'s the thrill of adventure, the serenity of creativity, or the joy of learning, our pursuits shape the vibrant hues of our daily lives. Embracing and nurturing these passions brings a sense of fulfillment and purpose.\r\n\r\nMindful Well-being: True vitality emerges when we prioritize our well-being—both physical and mental. From nourishing our bodies with wholesome nutrition to cultivating a mindful approach to stress and relaxation, a lifestyle attuned to well-being forms the foundation for a vibrant and resilient life.\r\n\r\nCultivating Connections: A vibrant lifestyle thrives on meaningful connections—with oneself, with others, and with the world around us. Building and nurturing relationships, fostering a sense of community, and embracing diversity create a rich tapestry of shared experiences that enhance the quality of our lives.\r\n\r\nBalancing Act of Work and Leisure: Striking a harmonious balance between work and leisure is an art. A fulfilling lifestyle embraces a work ethic that aligns with personal values and allows for moments of rejuvenation, play, and leisure. Achieving this equilibrium contributes to a more joyful and purposeful existence.\r\n\r\nContinuous Growth and Learning: A vibrant lifestyle is marked by a commitment to personal growth and lifelong learning. Embracing new challenges, acquiring new skills, and expanding our horizons contribute to a dynamic and enriching journey through life.\r\n\r\nHarmony with Nature: Connecting with the natural world is an integral part of a vibrant lifestyle. Whether it\'s enjoying outdoor activities, practicing sustainable living, or simply finding solace in the beauty of nature, fostering a harmonious relationship with the environment enhances our overall well-being.', '2023-12-11 08:37:59'),
(12, ' Savoring Life\'s Flavors', 'Balancing Passion, Well-being, and Personal Growth', 'Embark on a delectable journey through the enchanting world of food, where each dish is a story, and every meal is an opportunity to savor life\'s flavors. Join me as we celebrate the artistry of culinary delights, the richness of traditions, and the joy of creating memorable dining experiences.\r\n\r\nThe Palette of Tastes: Just as an artist blends colors to create a masterpiece, chefs craft dishes by harmonizing flavors. From the bold and savory to the sweet and delicate, the world of tastes invites us to indulge in a symphony of culinary delights that dance on our taste buds.\r\n\r\nCulinary Traditions and Heritage: Food is a cultural tapestry, woven with recipes passed down through generations. Whether it\'s the comforting warmth of a family recipe or the exploration of diverse global cuisines, culinary traditions connect us to our roots and create a sense of shared heritage.\r\n\r\nKitchen as a Canvas: In the heart of every home, the kitchen becomes a canvas where creativity flourishes. Experimenting with ingredients, trying new recipes, and infusing personal flair into dishes transform cooking into an art form—a delightful expression of love and passion.\r\n\r\nCulinary Exploration and Adventure: The world of food invites us on an exciting adventure of discovery. From street food stalls to fine dining establishments, each culinary experience unfolds a unique chapter, allowing us to explore diverse flavors, techniques, and cultural influences.\r\n\r\nNourishment for the Soul: Beyond the physical sustenance, food has the power to nourish the soul. Shared meals bring people together, fostering connections and creating moments of joy, laughter, and celebration. The act of breaking bread becomes a ritual that transcends mere nourishment.', '2023-12-11 08:34:08'),
(13, 'Bytes of Knowledge', 'Balancing Code, Creativity, and Campus Adventures', 'Embarking on the journey of being an IT student in college is like stepping into a dynamic digital landscape, where lines of code weave together with the tapestry of campus life. Join me in exploring the exhilarating world of an IT student, where challenges spark innovation, friendships are coded in binary, and learning is a perpetual adventure.\r\n\r\nCracking the Code of Academia: The life of an IT student involves unraveling complex algorithms, mastering programming languages, and embracing the ever-evolving world of technology. From coding assignments to software development projects, the academic journey is a continuous quest for knowledge and problem-solving.\r\n\r\nTech Meetups and Hackathons: Beyond the classroom, the IT student thrives in the electrifying atmosphere of tech meetups and hackathons. Collaborating with peers, solving real-world problems, and showcasing innovative solutions become exhilarating experiences that shape both skills and camaraderie.\r\n\r\nInnovative Projects and Start-up Dreams: The IT student is a digital architect, crafting innovative projects that push the boundaries of technology. From developing apps that simplify everyday tasks to envisioning startup ventures, creativity flourishes as students bring their tech-savvy visions to life.\r\n\r\nLate-Night Coding Sessions: As the night falls, the glow of computer screens illuminates dorm rooms and labs alike. Late-night coding sessions are a rite of passage, where lines of code become poetry, and debugging is a puzzle-solving adventure. The hum of servers and the click-clack of keyboards echo through the corridors.\r\n\r\nNetworking in the Digital Realm: Building a professional network is as crucial as crafting flawless code. IT students navigate the digital realm of LinkedIn, GitHub, and tech forums, establishing connections with industry professionals, mentors, and fellow enthusiasts who share a passion for innovation.\r\n\r\nBalancing Act: Academics and Campus Life: While code and projects are at the forefront, the IT student also finds balance in the diverse tapestry of campus life. From joining tech clubs to participating in campus events, there\'s an art to striking a harmonious balance between academic rigor and the vibrant social scene.\r\n\r\nEmbracing the Ever-Evolving Tech Landscape: The life of an IT student is a continuous journey of adaptation. Staying abreast of the latest technological trends, exploring emerging fields, and being adaptable to change are essential skills that pave the way for a successful career in the ever-evolving tech landscape', '2023-12-11 08:35:00');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `blogs`
--
ALTER TABLE `blogs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `blogs`
--
ALTER TABLE `blogs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
